---
- name: Preconfig
  hosts: demo

  tasks:
    - name: Installing Docker
      block:
        - name: Добавляем universe #репа с пакетами убунту
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
       
        - name: Установка дополнительных пакетов
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true
            cache_valid_time: 86400

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present #по умолчанию

        - name: Add Docker repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker
        
        - name: Install Docker-ce
          ansible.builtin.apt:
            name: docker-ce
            update-cache: true

        - name: Make sure Docker is running
          service:
            name: docker
            state: restarted
            enabled: true
      become: true

    - name: Завершение установки
      block:
        - name: Add user to Docker group
          ansible.builtin.user:
            name: "{{ansible_user}}"
            groups: docker
            append: true
        
        - name: Reboot
          ansible.builtin.reboot:
            reboot_timeout: 300
            msg: "System rebooted for Docker installation"
      become: true
